- hosts: localhost
  tasks:

    - name : Deploy the Service 
      k8s:
        state: present  
#        definition: ""
        validate_certs: no
        namespace: default
        src: service.yml
#        kubeconfig: ~/.kube
#        kubeconfig: ~/.kube

    # - name : Deploy the app 
    #   k8s:
    #     state: present  
    #     definition: ""
    #     validate_certs: no
    #     namespace: default
    #     connections:
    #       kubeconfig:  ~jenkins/.kube