- hosts: localhost
  tasks:

    - name : Test
      shell: cat ~/.kube/config


    - name : Deploy the Service 
      k8s:
        state: present  
        definition: ""
        validate_certs: no
        namespace: default
        kubeconfig: ~/.kube/config

    # - name : Deploy the app 
    #   k8s:
    #     state: present  
    #     definition: ""
    #     validate_certs: no
    #     namespace: default
    #     connections:
    #       kubeconfig:  ~jenkins/.kube